alertmanager:
  enabled: false
kubeControllerManager:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
grafana:
  adminUser: admin
  adminPassword: admin
  defaultDashboardsTimezone: browser
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL
prometheus:
  prometheusSpec:
    retention: 24h
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}
    resources:
      requests: { cpu: 100m, memory: 400Mi }
      limits: { cpu: 700m, memory: 1Gi }
prometheusOperator:
  resources:
    requests: { cpu: 50m, memory: 100Mi }
    limits: { cpu: 300m, memory: 300Mi }
